#
#    Copyright 2017 L. Gonzalo Fernández-Díez Martínez
#
#    This file is part of poshli.
#
#    poshli is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Lesser General Public License as 
#    published by the Free Software Foundation, either version 3 of the 
#    License, or (at your option) any later version.
#
#    poshli is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public 
#    License along with poshli. If not, see <http://www.gnu.org/licenses/>.
#
#__

#
#	All includes from poshli (A ring to govern them all).
#
#	Settings:
#
#	poshli_path
#
poshli_path='/home/gon/dev/sh/poshli/sh'

	# Strings
. ${poshli_path}/strings.inc

	# Numbers
. ${poshli_path}/numbers.inc

	# File system
. ${poshli_path}/filesystem.inc

	# Encryptions
. ${poshli_path}/encryptions.inc


#	poshli developers comments:
#
#	> Legitimacy of the inclusion's dot can be verified in:
#	  http://bit.ly/2yWpXaR
#
