#! /bin/sh -

#
#    Copyright 2017 L. Gonzalo Fernández-Díez Martínez
#
#    This file is part of lispo.
#
#    lispo is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Lesser General Public License as 
#    published by the Free Software Foundation, either version 3 of the 
#    License, or (at your option) any later version.
#
#    lispo is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with lispo.  If not, see <http://www.gnu.org/licenses/>.
#___

#
# This script is for debug purposes.
#

#	< config >

	libpath='/usr/lib/sh'

	str="String for T3st"
	num=577	

#	< config />


#	< includes >
	. $libpath/strings.inc
	. $libpath/encryptions.inc
#	< includes />

printf '\n%s\n' ' :: lispo testing :'

#	strings.inc
printf '\n%s\n'		"STRINGS		\$str is: \"$str\""
printf '\n%s\t'		' LOWER: ';			str_lower $str
printf '\n%s\t'		' UPPER: ';			str_upper $str

printf '\n\n'
